import { useEffect, useMemo, useRef, useState } from 'react'
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

const decisionColor = { Hire: '#16826c', Maybe: '#d88918', Reject: '#c55353' }
const scoreKeys = [['skill_match', 'Skills'], ['experience_match', 'Experience'], ['project_match', 'Projects'], ['education_match', 'Education'], ['certification_match', 'Certifications'], ['soft_skill_match', 'Soft skills'], ['semantic_similarity', 'Semantic']]
const previewJd = { job_title: 'Senior Platform Engineer', industry: 'Technology', seniority: 'Senior', min_years_experience: 5, weighted_skills: [{ skill: 'python', weight: 10 }, { skill: 'cloud architecture', weight: 10 }, { skill: 'aws', weight: 8 }, { skill: 'kubernetes', weight: 8 }, { skill: 'docker', weight: 7 }, { skill: 'sql', weight: 7 }] }
const candidateSeeds = [
  ['Maya Chen', 92, 'Hire'], ['Jordan Williams', 89, 'Hire'], ['Priya Nair', 87, 'Hire'], ['Avery Bennett', 85, 'Hire'], ['Noah Patel', 84, 'Hire'], ['Elena Rossi', 82, 'Hire'], ['Marcus Lee', 81, 'Hire'], ['Sofia Grant', 80, 'Hire'], ['Owen Brooks', 78, 'Hire'], ['Amara Lewis', 76, 'Hire'],
  ['Daniel Kim', 73, 'Maybe'], ['Isabel Moore', 71, 'Maybe'], ['Theo Martin', 69, 'Maybe'], ['Nora Shah', 68, 'Maybe'], ['Liam Cooper', 66, 'Maybe'], ['Zara Ahmed', 65, 'Maybe'], ['Ethan Wright', 63, 'Maybe'], ['Mila Torres', 61, 'Maybe'], ['Henry Davis', 59, 'Maybe'], ['Chloe King', 56, 'Maybe'],
  ['Arjun Mehta', 53, 'Reject'], ['Grace Hall', 51, 'Reject'], ['Caleb Young', 49, 'Reject'], ['Ivy Scott', 47, 'Reject'], ['Leo Baker', 45, 'Reject'], ['Ruby Clark', 43, 'Reject'], ['Ben Foster', 41, 'Reject'], ['Ella Morgan', 39, 'Reject'], ['Sam Rivera', 36, 'Reject'], ['Ava Price', 33, 'Reject'],
]
const previewResults = candidateSeeds.map(([name, score, decision], index) => {
  const matched = decision === 'Hire' ? ['python', 'cloud architecture', 'aws', 'kubernetes', 'docker', 'sql'] : decision === 'Maybe' ? ['python', 'aws', 'docker', 'sql'] : ['python', 'sql']
  const missing = ['cloud architecture', 'kubernetes', 'docker', 'aws', 'sql'].filter(skill => !matched.includes(skill))
  return { filename: `candidate-${index + 1}.pdf`, rank: index + 1, decision, resume: { name, email: `${name.toLowerCase().replace(' ', '.')}@example.com`, years_experience: Math.max(2, Math.round(score / 13)), skills: matched }, scores: { overall_score: score, skill_match: score, experience_match: Math.min(100, score + 3), project_match: Math.max(20, score - 2), education_match: 85, certification_match: 70, soft_skill_match: 88, semantic_similarity: Math.min(100, score + 2), matched_skills: matched, missing_skills: missing }, brief: `Decision\n${decision}\n\nReasoning\nCandidate assessment based on the role's required experience and technical capabilities.\n\nTop Strengths\nEvidence of relevant engineering experience and applicable technical skills.\n\nConcerns\nValidate the remaining role requirements during the next conversation.` }
})
const previewScreening = { jd: previewJd, results: previewResults, errors: [], summary: { total: 30, average_score: 64.5, top_candidate: 'Maya Chen', shortlisted: 20 } }

function formatFileName(file) { return file ? file.name : 'No file selected' }

export default function App() {
  const [view, setView] = useState('welcome')
  const [jd, setJd] = useState('')
  const [jdFile, setJdFile] = useState(null)
  const [resumes, setResumes] = useState([])
  const [screening, setScreening] = useState(null)
  const [activeTab, setActiveTab] = useState('Candidates')
  const [selected, setSelected] = useState(null)
  const [loading, setLoading] = useState(false)
  const [notice, setNotice] = useState('')
  const resumeInput = useRef(null)

  useEffect(() => { if (screening?.results?.length) setSelected(screening.results[0]) }, [screening])
  const results = screening?.results || []
  const shown = useMemo(() => [...results].sort((a, b) => a.rank - b.rank), [results])

  async function analyze() {
    if (!jd.trim() && !jdFile) return setNotice('Add a job description to begin.')
    if (!resumes.length) return setNotice('Add at least one candidate resume to begin.')
    setLoading(true); setNotice('')
    const form = new FormData(); form.append('job_description', jd)
    if (jdFile) form.append('jd_file', jdFile)
    resumes.forEach(file => form.append('resumes', file))
    try {
      const response = await fetch('/api/analyze', { method: 'POST', body: form }); const body = await response.json()
      if (!response.ok) throw new Error(body.detail || 'The screening run could not be completed.')
      setScreening(body); setActiveTab('Candidates'); setNotice(`Screening complete - ${body.results.length} candidates reviewed.`)
    } catch (error) { setNotice(error.message) } finally { setLoading(false) }
  }
  function openPipeline() { setScreening(previewScreening); setView('dashboard'); setActiveTab('Candidates'); setNotice('Candidate pipeline loaded.') }
  function download(kind) { const content = kind === 'json' ? JSON.stringify(screening, null, 2) : csv(results); const blob = new Blob([content], { type: kind === 'json' ? 'application/json' : 'text/csv' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `talent-lens-results.${kind}`; link.click(); URL.revokeObjectURL(url) }

  return <main className="app-shell"><header className="topbar"><a className="brand" href="/" onClick={e => { e.preventDefault(); setView('welcome'); setScreening(null) }}><span>*</span> Talent Lens</a><div className="topbar-note">Evidence-led candidate screening</div></header>
    {view === 'welcome' && <Welcome start={() => setView('intake')} openPipeline={openPipeline} />}
    {view === 'intake' && <Intake jd={jd} setJd={setJd} jdFile={jdFile} setJdFile={setJdFile} resumes={resumes} setResumes={setResumes} resumeInput={resumeInput} analyze={analyze} loading={loading} notice={notice} />}
    {view === 'dashboard' && screening && <Dashboard screening={screening} results={shown} selected={selected} setSelected={setSelected} activeTab={activeTab} setActiveTab={setActiveTab} newScreening={() => { setScreening(null); setView('intake') }} download={download} notice={notice} />}
  </main>
}

function Welcome({ start, openPipeline }) { return <section className="welcome"><div className="welcome-copy"><p className="eyebrow">Talent Lens recruiting portal</p><h1>Welcome, recruiters.</h1><p>Make every shortlist clearer, more consistent, and easier to defend. Talent Lens turns resumes into evidence-led hiring decisions.</p><div className="welcome-actions"><button className="primary welcome-primary" onClick={start}>Start a screening</button><button className="secondary" onClick={openPipeline}>Open candidate pipeline</button></div></div><aside className="welcome-panel"><p className="eyebrow">Candidate pipeline</p><h2>30 candidates across every review stage.</h2><div className="mini-candidates"><div><span className="avatar">10</span><p><b>Shortlisted</b><small>Candidates ready for the next round</small></p><strong>75+</strong></div><div><span className="avatar">10</span><p><b>Under review</b><small>Candidates needing a closer look</small></p><strong>55-74</strong></div><div><span className="avatar">10</span><p><b>Not progressing</b><small>Candidates below the role threshold</small></p><strong>&lt;55</strong></div></div><button className="text-button" onClick={openPipeline}>Open candidate pipeline -&gt;</button></aside></section> }
function Intake({ jd, setJd, jdFile, setJdFile, resumes, setResumes, resumeInput, analyze, loading, notice }) { return <section className="onboarding"><div className="hero-copy"><p className="eyebrow">New screening</p><h1>Find the right signal, faster.</h1><p>Build a consistent shortlist from resumes and role requirements, with transparent scores your team can stand behind.</p><div className="signal-row"><span>Structured extraction</span><span>Auditable scoring</span><span>Recruiter-ready briefs</span></div></div><section className="intake-card"><div className="step"><span>01</span><div><h2>Define the role</h2><p>Paste the job description or attach a file.</p></div></div><textarea value={jd} onChange={e => setJd(e.target.value)} placeholder="Paste the role overview, required skills, responsibilities, and experience level..." /><label className="file-control"><input type="file" accept=".pdf,.docx,.txt,.md" onChange={e => setJdFile(e.target.files[0] || null)} />Attach job description <small>{formatFileName(jdFile)}</small></label><div className="step"><span>02</span><div><h2>Add candidates</h2><p>Select one or more resumes to compare.</p></div></div><button className="dropzone" onClick={() => resumeInput.current?.click()}><b>Upload resumes</b><small>{resumes.length ? `${resumes.length} file${resumes.length > 1 ? 's' : ''} selected` : 'PDF, DOCX, TXT, or Markdown'}</small></button><input ref={resumeInput} className="hidden" type="file" accept=".pdf,.docx,.txt,.md" multiple onChange={e => setResumes(Array.from(e.target.files || []))} />{notice && <p className="notice">{notice}</p>}<button className="primary" disabled={loading} onClick={analyze}>{loading ? 'Analyzing candidates...' : 'Analyze candidates ->'}</button></section></section> }
function Dashboard({ screening, results, selected, setSelected, activeTab, setActiveTab, newScreening, download, notice }) { const [email, setEmail] = useState(''); const [emailLoading, setEmailLoading] = useState(false); const tabs = ['Candidates', 'Analytics', 'Role profile', 'Exports']; async function generateEmail(candidate) { setEmailLoading(true); setEmail(''); try { const response = await fetch('/api/interview-email', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ resume: candidate.resume, jd: screening.jd }) }); const body = await response.json(); if (!response.ok) throw new Error(body.detail || 'Could not create the interview email.'); setEmail(body.email) } catch (error) { setEmail('Unable to generate the email right now. Please try again.') } finally { setEmailLoading(false) } } return <><section className="dashboard-hero"><div><p className="eyebrow">Screening results</p><h1>{screening.jd.job_title || 'Candidate screening'}</h1><p>Review the shortlist and investigate the evidence behind every decision.</p></div><button className="secondary" onClick={newScreening}>New screening</button></section>{notice && <p className="toast">{notice}</p>}<section className="metrics"><Metric label="Candidates reviewed" value={screening.summary.total} /><Metric label="Average match" value={`${screening.summary.average_score}%`} /><Metric label="Top candidate" value={screening.summary.top_candidate} /><Metric label="Next round" value={screening.summary.shortlisted} /></section><nav className="tabs">{tabs.map(tab => <button className={tab === activeTab ? 'active' : ''} key={tab} onClick={() => setActiveTab(tab)}>{tab}</button>)}</nav>{activeTab === 'Candidates' && <CandidateTab results={results} selected={selected} setSelected={setSelected} email={email} emailLoading={emailLoading} generateEmail={generateEmail} />}{activeTab === 'Analytics' && <Analytics results={results} />}{activeTab === 'Role profile' && <Role jd={screening.jd} />}{activeTab === 'Exports' && <section className="export-card"><h2>Share the outcome</h2><p>Export the complete screening payload or a concise score table for your hiring team.</p><div><button className="secondary" onClick={() => download('csv')}>Download CSV</button><button className="primary compact" onClick={() => download('json')}>Download JSON</button></div></section>}</> }
function CandidateTab({ results, selected, setSelected, email, emailLoading, generateEmail }) { return <section className="candidate-layout"><div className="candidate-list"><div className="list-heading"><h2>Candidate ranking</h2><span>{results.length} total</span></div>{results.map(candidate => <button key={candidate.filename} className={`candidate-row ${selected?.filename === candidate.filename ? 'selected' : ''}`} onClick={() => setSelected(candidate)}><span className="rank">{candidate.rank}</span><span><b>{candidate.resume.name || candidate.filename}</b><small>{candidate.resume.years_experience || 0} years experience</small></span><span className="score">{candidate.scores.overall_score}<small>/100</small></span><span className="decision" style={{ color: decisionColor[candidate.decision] }}>{candidate.decision} - next round</span></button>)}</div>{selected && <CandidateDetail candidate={selected} email={email} emailLoading={emailLoading} generateEmail={generateEmail} />}</section> }
function CandidateDetail({ candidate, email, emailLoading, generateEmail }) { const { resume, scores } = candidate; const nextRound = scores.overall_score > 75; return <article className="detail"><div className="detail-header"><div><p className="eyebrow">Candidate profile</p><h2>{resume.name || candidate.filename}</h2><p>{resume.email !== 'Unknown' ? resume.email : 'No contact detail available'} - {resume.years_experience || 0} years experience</p></div><div className="big-score">{scores.overall_score}<span>/100</span></div></div>{nextRound && <section className="next-round"><div><b>Ready for the next round</b><span>This candidate has met the interview threshold.</span></div><button className="primary compact" onClick={() => generateEmail(candidate)} disabled={emailLoading}>{emailLoading ? 'Generating...' : 'Generate interview mail'}</button></section>}{email && <section className="email-preview"><b>Interview invitation draft</b><pre>{email}</pre></section>}<div className="chips"><Chip title="Matched" values={scores.matched_skills} kind="match" /><Chip title="Focus areas" values={scores.missing_skills} kind="missing" /></div><h3>Score breakdown</h3><div className="breakdown">{scoreKeys.map(([key, label]) => <div key={key}><span>{label}</span><b>{Math.round(scores[key] || 0)}%</b><i><em style={{ width: `${scores[key] || 0}%` }} /></i></div>)}</div><h3>Recruiter brief</h3><div className="brief">{candidate.brief ? candidate.brief.replace(/###\s*/g, '') : 'No recruiter brief available.'}</div></article> }
function Analytics({ results }) { const statuses = ['Hire', 'Maybe', 'Reject'].map(name => ({ name, value: results.filter(r => r.decision === name).length })); const ranks = results.map(r => ({ name: r.resume.name?.split(' ')[0] || r.filename, score: r.scores.overall_score, decision: r.decision })); return <section className="analytics"><ChartCard title="Candidate match scores"><ResponsiveContainer width="100%" height={310}><BarChart data={ranks}><CartesianGrid vertical={false} stroke="#e5e7eb" /><XAxis dataKey="name" /><YAxis domain={[0, 100]} /><Tooltip /><Bar dataKey="score" radius={[6, 6, 0, 0]}>{ranks.map(item => <Cell key={item.name} fill={decisionColor[item.decision]} />)}</Bar></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Decision mix"><ResponsiveContainer width="100%" height={310}><PieChart><Pie data={statuses} dataKey="value" nameKey="name" innerRadius={72} outerRadius={106} paddingAngle={3}>{statuses.map(item => <Cell key={item.name} fill={decisionColor[item.name]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="legend">{statuses.map(s => <span key={s.name}><i style={{ background: decisionColor[s.name] }} />{s.name}: {s.value}</span>)}</div></ChartCard></section> }
function Role({ jd }) { return <section className="role-card"><p className="eyebrow">Role requirements</p><h2>{jd.job_title}</h2><div className="role-meta"><span><b>Industry</b>{jd.industry || 'Not specified'}</span><span><b>Seniority</b>{jd.seniority || 'Not specified'}</span><span><b>Minimum experience</b>{jd.min_years_experience || 0} years</span></div><h3>Weighted skills</h3><div className="skill-grid">{(jd.weighted_skills || []).map(item => <div key={item.skill}><span>{item.skill}</span><b>{item.weight}/10</b></div>)}</div></section> }
function Metric({ label, value }) { return <div className="metric"><span>{label}</span><b>{value}</b></div> }
function Chip({ title, values = [], kind }) { return <div className={`chip-group ${kind}`}><span>{title}</span><div>{values.length ? values.map(value => <i key={value}>{value}</i>) : <small>None identified</small>}</div></div> }
function ChartCard({ title, children }) { return <article className="chart-card"><h2>{title}</h2>{children}</article> }
function csv(results) { const headers = ['Rank', 'Candidate', 'Score', 'Decision', 'Years experience', 'Matched skills', 'Missing skills']; const rows = results.map(r => [r.rank, r.resume.name || r.filename, r.scores.overall_score, r.decision, r.resume.years_experience || 0, (r.scores.matched_skills || []).join('; '), (r.scores.missing_skills || []).join('; ')]); return [headers, ...rows].map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n') }
